### ISSUE TITLE
Not friendly

### ISSUE THREAD

**Issue by seagullbird** [Forec/web-api#1]
Examples in JSON API using `wget`, which downloads response by default rather than print it on the screen, to show how your API works, are not that user friendly coz **I don't want to have weird files downloaded on my computer you idiot!**

`curl` or `httpie` recommended :)

**Comment by Forec** [comment]
Thanks for your `curl` . Come back to dormitory you idiot!

**Comment by seagullbird** [comment]
Nah actually `httpie` is more recommended in your situation, can check them out on github.
( I have no idea that you don't know these two before? )
I'm studying don't bother me 💯
